'use client';
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, ShieldCheck, FlaskConical } from 'lucide-react';
import { Brand } from './brand';
import { api } from '@/lib/api';
export function Login({localEnabled}:{localEnabled:boolean}) {
  const router=useRouter();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [workspace,setWorkspace]=useState('');
  useEffect(()=>{api('/auth/me').then(()=>router.replace('/app')).catch(()=>{});},[router]);
  async function local(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{await api('/auth/local',{method:'POST',data});router.push('/app');}catch(e){setError(e instanceof Error?e.message:'Unable to sign in.');}finally{setBusy(false)}}
  async function google(){setBusy(true);setError('');try{const {initializeApp,getApps}=await import('firebase/app');const {getAuth,GoogleAuthProvider,signInWithPopup,signOut}=await import('firebase/auth');const config={apiKey:process.env.NEXT_PUBLIC_FIREBASE_API_KEY,authDomain:process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,projectId:process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,appId:process.env.NEXT_PUBLIC_FIREBASE_APP_ID};if(!config.apiKey||!config.authDomain)throw new Error('Managed sign-in has not been configured for this deployment.');const auth=getAuth(getApps()[0]||initializeApp(config));const result=await signInWithPopup(auth,new GoogleAuthProvider());/* A workspace is named by the person creating it, never defaulted silently. */const name=workspace.trim();await api('/auth/exchange',{method:'POST',data:{id_token:await result.user.getIdToken(),...(name?{organization_name:name}:{})}});await signOut(auth);router.push('/app');}catch(e){setError(e instanceof Error?e.message:'Unable to sign in.');}finally{setBusy(false)}}
  return <div className="login-page"><div className="login-aside"><Brand/><div><div className="eyebrow">PROVE. REMEMBER. RE-PROVE.</div><h1>The next version<br />should remember<br /><em>the last lesson.</em></h1><p>Keep your security properties, useful fixes, and release evidence connected.</p></div><span className="login-caption"><ShieldCheck size={17}/> Change assurance for AI agents</span></div><main id="main" className="login-main"><div className="login-card"><Link href="/" className="back-link">← Back to ThreatVeil</Link><h2>Your security workspace.</h2><p>See what changed, which conclusions still hold, and whether the clearance is current. Next you choose: connect your own agent, or explore an example.</p>{localEnabled?<><div className="local-warning"><FlaskConical size={18}/><div><strong>Local development identity</strong><span>This identity is for the loopback development environment. It is not a verified production account.</span></div></div><form onSubmit={local}><label>Your name<input name="name" required maxLength={120} autoComplete="name" placeholder="Alex Morgan"/></label><label>Email<input name="email" type="email" required autoComplete="email" placeholder="you@company.com"/></label><label>Organization<input name="organization_name" required maxLength={160} autoComplete="organization" placeholder="Your organization"/></label><button className="button dark" disabled={busy}>{busy?'Opening workspace…':'Open local workspace'}<ArrowRight size={17}/></button></form></>:<><label className="workspace-name">Workspace name<input value={workspace} onChange={e=>setWorkspace(e.target.value)} maxLength={120} placeholder="Your company or team"/><small>Used to name your organization. You can change it later in settings.</small></label><button className="button dark" onClick={google} disabled={busy}>{busy?'Signing in…':'Start free with Google'}<ArrowRight size={17}/></button></>}{error&&<div className="notice error" role="alert">{error}</div>}<p className="login-footnote">Sessions are protected by server-verified identity and organization permissions. <Link href="/security">Security & trust</Link></p></div></main></div>
}
